### ISSUE TITLE
pytorch and torchvision version

### ISSUE THREAD

**Issue by qe903121** [Horizon2333/imagenet-autoencoder#6]
Sorry, could you please provide versions pytorch and torchvision? I can't seem to read the weights as it appears that the version is too old. I am using torch1.4 and torch0.5.

**Comment by Horizon2333** [comment]
Sorry for the late reply. We have tested the code under pytorch 1.8.0. But I think pytorch 1.4.0 can also load the checkpoints. Can you provide more detailed information?

**Comment by qe903121** [comment]
@Horizon2333 
Thank you for your reply. Despite using Pytorch 1.4, it's possible that it cannot be used due to the GPU driver being too old

> => parse the args ...
=> torch version : 1.4.0
=> modeling the network ...
Traceback (most recent call last):
  File "tools/encode.py", line 80, in <module>
    main(args)
  File "tools/encode.py", line 51, in main
    model = builder.BuildAutoEncoder(args)
  File "./models/builer.py", line 28, in BuildAutoEncoder
    model = nn.DataParallel(model).cuda()
  File "/usr/local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 304, in cuda
    return self._apply(lambda t: t.cuda(device))
  File "/usr/local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 201, in _apply
    module._apply(fn)
  File "/usr/local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 201, in _apply
    module._apply(fn)
  File "/usr/local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 201, in _apply
    module._apply(fn)
  [Previous line repeated 3 more times]
  File "/usr/local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 223, in _apply
    param_applied = fn(param)
  File "/usr/local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 304, in <lambda>
    return self._apply(lambda t: t.cuda(device))
  File "/usr/local/lib/python3.8/site-packages/torch/cuda/__init__.py", line 196, in _lazy_init
    _check_driver()
  File "/usr/local/lib/python3.8/site-packages/torch/cuda/__init__.py", line 104, in _check_driver
    raise AssertionError("""
AssertionError:
The NVIDIA driver on your system is too old (found version 10000).
Please update your GPU driver by downloading and installing a new
version from the URL: http://www.nvidia.com/Download/index.aspx
Alternatively, go to: https://pytorch.org to install
a PyTorch version that has been compiled with your version
of the CUDA driver.

Perhaps I should upgrade my GPU driver first :)

**Comment by Horizon2333** [comment]
@qe903121 
I'm sorry. What I said before was wrong. I have created an environment with Pytorch 1.4. The code encountered an error while loading the checkpoint. I guess this is because the format that Pytorch saves checkpoints has changed after Pytorch 1.4. In the error message, the version of the Pytorch file for the checkpoint is 3, while Pytorch 1.4 supports up to 2. 
So you may need to update the driver and PyTorch at the same time
